name: alsagr_app
description: A new Flutter project.
publish_to: "none"
version: 1.0.5+11

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  bot_toast: ^4.1.3
  cached_network_image: ^3.3.0
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.12.1
  enefty_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  file_picker: ^6.0.0
  firebase_core: ^2.20.0
  flutter:
    sdk: flutter
  flutter_form_builder: ^9.1.1
  flutter_localization: ^0.1.14
  flutter_pdfview: ^1.3.2
  font_awesome_flutter: ^10.3.0
  get: ^4.6.6
  http: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.1
  path_provider: ^2.1.1
  platform: ^3.1.3
  responsive_framework: ^1.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  timeago: ^3.5.0
  url_launcher: ^6.1.6

# icons_launcher:
#   image_path: "assets/app_icon.png"
#   platforms:
#     android:
#       enable: true
#     ios:
#       enable: true
dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - shorebird.yaml
