name: alsagr_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  carousel_slider: ^4.2.1
  eva_icons_flutter: ^3.1.0
  expandable: ^5.0.1
  flutter:
    sdk: flutter
  url_launcher: ^6.1.6
  font_awesome_flutter: ^10.3.0
  file_picker: ^4.1.4
  enefty_icons: ^1.0.5
  flutter_form_builder: ^9.1.1
  firebase_core: ^2.15.1
  cloud_firestore: ^4.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/